# Generated by Django 3.2.12 on 2022-08-29 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_testmodel2_pick_up_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('pick_up_date', models.DateField(blank=True, null=True)),
                ('pick_up_time', models.TimeField(blank=True, null=True)),
                ('pick_up_comment', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='main.CategoryModel')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.institutionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
