# Generated by Django 3.2.12 on 2022-08-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_testmodel3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='pick_up_time',
            field=models.TimeField(),
        ),
    ]
