# Generated by Django 3.2.12 on 2022-08-31 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_donationmodel_pick_up_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.DeleteModel(
            name='TestModel2',
        ),
        migrations.DeleteModel(
            name='TestModel3',
        ),
    ]
